version: '3'

services:
   frontend:
     image: certphisher/frontend:latest
     restart: on-failure
     ports:
      - "5000:5000"
     depends_on:
      - backend
      - db
     links:
      - "db:mongo"
      - "backend:backend"

   backend:
     image: certphisher/backend:latest
     restart: on-failure
     depends_on:
      - db
     links:
      - "db:mongo"

   db:
     image: mongo:4.4.6
     volumes:
          - ./mongodb/data:/data/db
     restart: on-failure